### ISSUE TITLE
아두이노 - 신호등 실제 구현

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#13]
1. 좌측 신호등 테스트
2. 신호등 회로 구현
3. 신호 전환 프로그램 구현
   - 버튼을 누르면 차량 -> 보행자 
   - 버튼 을 다시 누르면 보행자 -> 차량

**Comment by vertex50** [comment]
1.
좌측 신호등 테스트과정에서 Uno보드를 인식 못하는 오류 발생. 
Uno의 성능이 문제인지 보드고장인지는 보유하고있는 Uno보드가 하나인 관계로 오류 원인 체크못함.
-  다만 우리가 사용할 보드가 Mega ADK인데 MegaADK보드에서는 오류 없이 작동함.
-  Arduino Mega ADK보드 상에서 좌측신호등 또한 문제없이 작동함을 확인함.

소스와 mega보드 문제없음.

**Comment by vertex50** [comment]
2.
신호등 회로구현
회로구성 사이트에서 Mega보드가 없는 관계로 Uno보드를 기반으로 작성. Uno가 Mega에 비해 핀 개수가 모자라 left만 구성,button의 mega상 핀번호는 22번임. 그 외 아래 그림에서 핀번호는 소스와 동일
버튼의 경우 센서가 -/+/signal로 구성되어 있다. 버튼의 signal은 mega보드 22번핀에 연결된다. 
![scw_left_pin](https://cloud.githubusercontent.com/assets/19426761/16722449/a3f37aec-4781-11e6-8454-2c97b75f5a36.png)
신호등 회로는 위와 크게 다르지 않음.

**Comment by vertex50** [comment]
3.
신호전환프로그램
1)차량신호->보행자신호로 전환. 버튼을 다시 눌렀을 경우 2)보행자에서->차량신호 전환이 되지 않음
이것은 버튼이 단순 push버튼이기 때문. 1회 클릭시 1)케이스로 진행하게 2회 클릭시 2)에 해당하는
케이스로 전환되게 하려 했으나, button클릭시 HIGH/LOW로 인지하기 때문에 1회 누를경우 값이 하나가 증가되는 것이 아니라 LOW상태가 되고 숫자가 급격히 증가함. 컨트롤 할 수 없음.
- 현재 차량신호에 대기하다가 버튼 클릭시 보행자 신호로 전환되는 형태 구현.
- on/off버튼이 주어지거나 혹은 push버튼을 여러개의 핀에 연결하는 방법을 고려해 볼수 있음.

ON/OFF버튼 필요. 및 요구사항 수정 필요.
