### ISSUE TITLE
아두이노 UNO - LED 제어 버그

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#2]
아두이노 LED 제어 버그 재 구현

아두이노에서 다량의 LED제어 시 제어가 프로그램된 방식과 다른방식으로 점등한다는 상황 있음, 실제로 재현을 통하여 검증이 필요

**Comment by vertex50** [comment]
테스트 해본결과 기존 오류와 다른 형태의 오류가 존재함.
7번 핀 car신호등 red색의 문제였는데,
문제원인추정
1번째는 LED의 고장
2번째는 A(암페어)가 모자라서그럴것이다.
3번째는 소스의 문제일 것이다.
4번째는 Uno의 GPIO가 고장이 났을것이다.
5번째는 혹시 선에도 문제가 있지 않을까.
원인 하나하나 확인해본결과 LED와 A(암페어)문제는 아니였고 소스를 수정해 테스트 해본결과
소스가 오류의 원인은 아니였고 GPIO또한 문제가 없었다. 마지막으로 선을 바꿔 연결해본 결과
불이 들어왔고 선의 문제였다. 위의 고장난 선은 랩장에게 인수인계했고 폐기처분 했다고 한다.
그 이후 Right쪽의 불은 정상적으로 동작했다.

**Comment by KwangEun** [comment]
그러면 기존의 오류는 결국 발생할 여지가 있다는 건데.....
목표 설정의 수정이 필요해 보임
