### ISSUE TITLE
조도센서 - 알고리즘 정리

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#21]
1. 알고리즘 정리 및 주석

**Comment by LeeDeukHui** [comment]
int LED[] = {2,4, 6, 8};
int Laiser_CDS[] = {0,1,2,3}; // 
int std_CDS[] = {4,5,6,7}; // 자연광을 측정하는 조도센서들의 핀

void setup()
{
  Serial.begin(9600);
  for(int i=0; i<3; i++){
    pinMode(LED[i], OUTPUT);
  }
}
void loop()
{
  int cdsvalue[8]; // 8개의 조도센서 값을 저장하는 배열
  int std_avg = 0; //자연광의 평균값을 나타내는 변수
  int Laiser_avg = 0;  // 레이저의 평균값을 나타내는 변수
  for(int i=0; i<8; i++){
    if(i<4){ // 자연광의 값
     cdsvalue[i] = analogRead(Laiser_CDS[i]);
      Laiser_avg += cdsvalue[i];  // 레이저를 수신하는 조도센서들의 값들을 합
    }else{
      cdsvalue[i] = analogRead(std_CDS[i-4]);
      std_avg += cdsvalue[i]; // 자연광을 측정한 조도센들의 값들을 합
    }
  }
  Serial.print("std_avg = ");
  Serial.println((std_avg+cdsvalue[0])/5);
  Serial.print("Laiser_avg = "); // 시리얼 모니터에 값 출력
  Serial.println( Laiser_avg/4);
  Serial.print("std_avg-Laiser_avgv = ");
  Serial.println( (std_avg+cdsvalue[0])/5-Laiser_avg/4);
  Serial.println("");
  for (int i=0; i<8; i++){
    Serial.print("@");
    Serial.print(i);
    Serial.print(" = ");
    Serial.println(cdsvalue[i]);
  }
  if((std_avg+cdsvalue[0])/5-Laiser_avg/4>60){ // 레이저가 수신될때 
    for(int i=0; i<3; i++){
      digitalWrite(LED[i], HIGH);
      delay(100);
    }for(int i=0; i<3; i++){
      digitalWrite(LED[i], LOW);
      delay(100);
    }
  }else{
    for(int i=4; i>=0; i--){
      digitalWrite(LED[i], HIGH);
      delay(100);
    }for(int i=4; i<=0; i--){
      digitalWrite(LED[i], LOW);
      delay(100);
    }
  }
}

**Comment by LeeDeukHui** [comment]
![kakaotalk_20160710_153004363](https://cloud.githubusercontent.com/assets/19421401/17171566/2bc74906-542c-11e6-869f-93fa81c30e79.jpg)
