### ISSUE TITLE
모형 설계

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#24]
크기, 재료(아크릴재질...) 리스트 정리

**Comment by LeeDeukHui** [comment]
![2016-07-30_22-05-17](https://cloud.githubusercontent.com/assets/19421401/17270643/6a943068-56a2-11e6-9361-d3695921ee8a.png)
신호등 모델 A

**Comment by LeeDeukHui** [comment]
# **신호등 모델 A**

`외형은 변경가능, 대략적인 신호, 투광기, 감지기, CCTV....등의 위치만 고려`

![model_a](https://cloud.githubusercontent.com/assets/19421401/17270699/73a259b2-56a4-11e6-970b-d9d04d1d569a.png)

**Comment by LeeDeukHui** [comment]
# **신호등 모델 B**

![model_b](https://cloud.githubusercontent.com/assets/19421401/17270809/94202ff0-56a6-11e6-93ae-16b28308570c.png)

**Comment by LeeDeukHui** [comment]
# 보행자 신호등 알고리즘 구현

int pedestrian_LED[12]; // LED
int pedestrian = 30; // 보행자가 건너기 위해 누르는 버튼
int pass_light = 0; //  신호등 불빛 0 == RED 1 == GREEN
int pedestrian_push = 0; // 
int pedestrian_out = 40; // 보행자 존재 유무
int on_off[2]; // HIGH, LOW
int num = 0; // 신호등 변환 속도 기준
int _speed = 200; // 신호등 변환 속도
const int GREEN = 0;
const int RED = 6;
void setup() {
  on_off[0] = LOW;
  on_off[1] = HIGH;
  Serial.begin(9600);
  for (int i = 0; i < 12; i++) {
    pedestrian_LED[i] = i + 2;
    pinMode(pedestrian_LED[i], OUTPUT);
  }
  pinMode(pedestrian, INPUT);
  pinMode(pedestrian_out, INPUT);
}

// **\* 조건에 따라 LED 제어하는 함수(각 색깔의 모든 LED) ***

void total_LED_control(int _status, int pass_light) {
  for (int i = pass_light; i < pass_light + 6; i++) {
    digitalWrite(pedestrian_LED[i], on_off[_status]);
  }
}

// **\* 조건에 따라 LED 제어하는 함수(각 색깔의 하나의 LED를 차례대로) ***

void LED_off() {
  int flag = num / _speed - 1;
  if (num % _speed == 0 && pass_light == 0) {    //  
    digitalWrite(pedestrian_LED[flag + 6], on_off[0]);
  }
  else if (num % _speed == 0 && pass_light == 1) {
    digitalWrite(pedestrian_LED[flag - 6], on_off[0]);
  }

  if (flag == 5) { // RED LED 소등 완료
    total_LED_control(1, GREEN);
    pass_light = 1;
  }
  else if (flag == 11) {  // GREEN LED 소등 완료
    num = 0;
    total_LED_control(1, RED);
    pass_light = 0;
    pedestrian_push = 0;
  }
}

// **\* 보행자가 건널 의사를 밝혔는지에 따라 신호등을 제어하는 함수 ***

void pedestrian_check(int pedestrian_check) {
  if (pedestrian_check == 1 && num == 0) {
    pedestrian_push = 1;
    num = 0;
  }
  if (digitalRead(pedestrian_out) == 1 && pass_light == 0) {
    total_LED_control(1, RED);
    pedestrian_push = 0;
    num = 0;
  }
  if (pedestrian_push == 1) {
    num++;
    LED_off();
    Serial.println(num);
  }
}

void loop() {
  total_LED_control(1, RED);
  while (1) {
    pedestrian_check(digitalRead(pedestrian));
  }
}

**Comment by LeeDeukHui** [comment]
http://www.makeall.com/subpage.php?p=makerspace
