### ISSUE TITLE
조도센서 - 레이저 수신 장치 제작

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#4]
조도 센서를 실제 기판에 납땜하고 이를 아두이노에서 입력으로 받아들이도록 제작

**Comment by LeeDeukHui** [comment]
error

**Comment by LeeDeukHui** [comment]
아날로그 핀에 조도센서를 여러개 연결하여 각 조도센서의 값 불러오기
    -> 하나의 핀만 동작(디지털핀 또한)

**Comment by KwangEun** [comment]
회로 구성의 확인이 필요한듯 ㅇㅅㅇ... 작년엔 6개 다 따로따로 받았어 ㅇㅇ!
