### ISSUE TITLE
아두이노 - 신호등 체계 구현

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmartCrosswalk_Sensor#6]
아두이노를 사용하여 보행자 신호등 과 차량 신호등을 전환할 수 있는 알고리즘

**Comment by vertex50** [comment]
- 1)차량신호->보행자신호로 전환. 버튼을 다시 눌렀을 경우 2)보행자에서->차량신호 전환 이 목표

num이라는 변수를 두고 버튼이 눌렸을 경우 num에 갑슬 누적시켜 홀수의 경우 1)로 짝수일 경우 2)로 전환되게 하려고 했음. 1)의 경우는 가능하지만 2)의 경우가 불가능함. 
이것은 버튼이 단순 push버튼이기 때문. 1회 클릭시 1)케이스로 진행하게 2회 클릭시 2)에 해당하는 케이스로 전환되게 하려 했으나, button클릭시 HIGH/LOW로 인지하기 때문에 1회 누를경우 값이 하나가 증가되는 것이 아니라 LOW상태가 되고 숫자가 급격히 증가함. 컨트롤 할 수 없음.
- on/off버튼이 주어지거나 혹은 push버튼을 여러개의 핀에 연결하는 방법을 고려해 볼수 있음.
- 현재 차량신호에 대기하다가 버튼 클릭시 보행자 신호로 전환되는 형태 구현.
